apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-Deplyment
  labels: 
    app: myapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
